# Generated by Django 4.2.5 on 2023-09-06 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Music', 'Музыка'), ('Replicas', 'Реплики')], max_length=20)),
                ('audio', models.FileField(upload_to='audios/')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Cinematic', 'Синематики'), ('GameProcess', 'Игровой Процесс')], max_length=20)),
                ('video', models.FileField(upload_to='videos/')),
            ],
        ),
    ]
